// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlUguRJe-C_e5wnsrVD8jXRwkWR8uayO8',
    appId: '1:939687044050:web:105d7492396891aef5de0b',
    messagingSenderId: '939687044050',
    projectId: 'notly-d1aaa',
    authDomain: 'notly-d1aaa.firebaseapp.com',
    storageBucket: 'notly-d1aaa.appspot.com',
    measurementId: 'G-4MJLD8R8CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBMr9Ra0jHjgAJGtR7D4-9US1JY-5fYU',
    appId: '1:939687044050:android:ebd5cbcefa6fede7f5de0b',
    messagingSenderId: '939687044050',
    projectId: 'notly-d1aaa',
    storageBucket: 'notly-d1aaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR3PGn9ev-QIgdO0W5i1W_iOsKJpRItT4',
    appId: '1:939687044050:ios:b61cfb50e457c0cdf5de0b',
    messagingSenderId: '939687044050',
    projectId: 'notly-d1aaa',
    storageBucket: 'notly-d1aaa.appspot.com',
    iosClientId:
        '939687044050-6qd414mmfha8f5ig35vucdncodafanh3.apps.googleusercontent.com',
    iosBundleId: 'eg.notly.notly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR3PGn9ev-QIgdO0W5i1W_iOsKJpRItT4',
    appId: '1:939687044050:ios:b61cfb50e457c0cdf5de0b',
    messagingSenderId: '939687044050',
    projectId: 'notly-d1aaa',
    storageBucket: 'notly-d1aaa.appspot.com',
    iosClientId:
        '939687044050-6qd414mmfha8f5ig35vucdncodafanh3.apps.googleusercontent.com',
    iosBundleId: 'eg.notly.notly',
  );
}
